version: "3.9"
services:
  vaadin-1:
    image: vaadin/my-app
    build: ../../../my-app
    ports:
      - "8080:8080"
    environment:
      APP_NAME: My App on vaadin-1
  vaadin-2:
    image: vaadin/my-app
    build: ../../../my-app
    ports:
      - "7070:8080"
    environment:
      APP_NAME: My App on vaadin-2
  web:
    image: nginx
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "9090:80"
