ProxyPass           /ui/HILLA/push     ws://vaadin:8080/HILLA/push
ProxyPass           /ui/VAADIN/push    ws://vaadin:8080/ui/VAADIN/push
ProxyPass           /ui/HILLA/         ajp://vaadin:8009/HILLA/
ProxyPass           /                  ajp://vaadin:8009/
