# Running stage: the part that is used for running the application
FROM temurin:21
COPY target/*.jar /usr/app/app.jar
RUN useradd -m myuser
USER myuser
EXPOSE 8080
CMD [ "java", "-jar", "/usr/app/app.jar" ]
