version: "3.9"
services:
  vaadin:
    image: vaadin/my-app
    build: ../../../my-app
    ports:
      - "8080:8080"
    environment:
      VAADIN_URL_MAPPING: /ui/*
      VAADIN_PUSH_URL: /VAADIN/push
  http:
    image: "httpd:latest"
    ports:
      - "9090:80"
    volumes:
      - ../../httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./vaadin.conf:/usr/local/apache2/conf/extra/httpd-vaadin-http.conf
