services:
  vaadin-1:
    image: vaadin/my-app:${MY_APP_VERSION:-latest}
    build: ../../../my-app
    ports:
      - "8080:8080"
    environment:
      - VAADIN_PUSH_TRANSPORT=SERVER_SENT_EVENTS
      - APP_NAME=My App on vaadin-1
  vaadin-2:
    image: vaadin/my-app:${MY_APP_VERSION:-latest}
    build: ../../../my-app
    ports:
      - "7070:8080"
    environment:
      - VAADIN_PUSH_TRANSPORT=SERVER_SENT_EVENTS
      - APP_NAME=My App on vaadin-2
  web:
    depends_on:
      - vaadin-1
      - vaadin-2
    image: "${NGINX_IMAGE:-nginx:1.31.6}"
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "9090:80"
