#!/usr/bin/env bash
# Regenerate per-scenario README.md files from scenarios.tsv.
#
# For each row in scenarios.tsv (`proxy/scenario | description | paths`):
#   - Apache scenarios inline vaadin.conf (and vaadin-location.conf if present).
#   - NGINX scenarios inline whatever the docker-compose.yml mounts to
#     /etc/nginx/templates/default.conf.template (shared template or scenario-local).
#
# Re-running this script is idempotent. Edit descriptions in scenarios.tsv,
# not in the generated README.md files.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
catalog="$repo_root/scenarios.tsv"

[[ -f $catalog ]] || { echo "scenarios.tsv not found at $catalog" >&2; exit 1; }

proxy_label() {
    case "$1" in
        apache-httpd/http)      echo "Apache HTTPD (HTTP)" ;;
        apache-httpd/ajp)       echo "Apache HTTPD (AJP)" ;;
        apache-httpd/https)     echo "Apache HTTPD (HTTPS)" ;;
        apache-httpd/ajp-https) echo "Apache HTTPD (AJP + HTTPS)" ;;
        nginx/http)             echo "NGINX" ;;
        nginx/https)            echo "NGINX (HTTPS)" ;;
        *)                      echo "$1" ;;
    esac
}

# Public proxy origin for a given proxy directory.
proxy_origin() {
    case "$1" in
        */https|*/ajp-https) echo "https://localhost:9443" ;;
        *)                   echo "http://localhost:9090" ;;
    esac
}

# Print a file's contents, ensuring the output ends with exactly one newline
# so the closing fence we emit lands on its own line.
cat_with_trailing_newline() {
    awk 'NR>1{print prev} {prev=$0} END{if (NR>0) print prev}' "$1"
}

# Resolve the path that docker-compose.yml mounts to
# /etc/nginx/templates/default.conf.template, relative to the scenario dir.
nginx_template_for() {
    local scenario_dir="$1"
    local compose="$scenario_dir/docker-compose.yml"
    local rel
    rel=$(grep -E '^\s*-\s+\S+:/etc/nginx/templates/default\.conf\.template' "$compose" \
          | head -1 \
          | sed -E 's|^\s*-\s+([^:]+):/etc/nginx/templates/default\.conf\.template.*$|\1|')
    [[ -z $rel ]] && return 1
    (cd "$scenario_dir" && cd "$(dirname "$rel")" && echo "$PWD/$(basename "$rel")")
}

write_readme() {
    local key="$1" description="$2" paths="$3"
    local scenario_dir="$repo_root/$key"
    local compose="$scenario_dir/docker-compose.yml"

    if [[ ! -f $compose ]]; then
        echo "skip (no docker-compose.yml): $key" >&2
        return 0
    fi

    local proxy_dir="${key%/*}"        # e.g. apache-httpd/http
    local scenario_name="${key##*/}"   # e.g. root-context
    local title="$(proxy_label "$proxy_dir") — $scenario_name"
    local origin="$(proxy_origin "$proxy_dir")"

    local readme="$scenario_dir/README.md"
    {
        echo "<!-- AUTOGENERATED by scripts/gen-readmes.sh — edit scenarios.tsv -->"
        echo "# $title"
        echo
        echo "$description"
        echo
        echo "Proxy URL on \`$origin\`: \`$paths\`"
        echo
        echo "## Configuration"
        echo
        echo "See [docker-compose.yml](./docker-compose.yml) for service definitions."
        echo

        case "$proxy_dir" in
            apache-httpd/*)
                echo "Apache HTTPD config (\`vaadin.conf\`):"
                echo
                echo '```apache'
                cat_with_trailing_newline "$scenario_dir/vaadin.conf"
                echo '```'
                if [[ -f $scenario_dir/vaadin-location.conf ]]; then
                    echo
                    echo "Additional location-scoped rules (\`vaadin-location.conf\`):"
                    echo
                    echo '```apache'
                    cat_with_trailing_newline "$scenario_dir/vaadin-location.conf"
                    echo '```'
                fi
                ;;
            nginx/*)
                local tpl
                if tpl=$(nginx_template_for "$scenario_dir"); then
                    local tpl_rel="${tpl#$repo_root/}"
                    echo "NGINX template (\`$tpl_rel\`):"
                    echo
                    echo '```nginx'
                    cat_with_trailing_newline "$tpl"
                    echo '```'
                else
                    echo "_No NGINX template mount detected in docker-compose.yml._"
                fi
                ;;
        esac
    } > "$readme"

    echo "wrote $readme"
}

while IFS= read -r raw_line; do
    # Strip CR, trim, skip blanks and comments.
    line="${raw_line%$'\r'}"
    [[ -z ${line// } ]] && continue
    [[ ${line:0:1} == "#" ]] && continue

    # Pipe-separated: key | description | paths
    IFS='|' read -r key description paths <<< "$line"
    key="${key#"${key%%[![:space:]]*}"}"; key="${key%"${key##*[![:space:]]}"}"
    description="${description#"${description%%[![:space:]]*}"}"; description="${description%"${description##*[![:space:]]}"}"
    paths="${paths#"${paths%%[![:space:]]*}"}"; paths="${paths%"${paths##*[![:space:]]}"}"

    [[ -z $key ]] && continue
    write_readme "$key" "$description" "$paths"
done < "$catalog"
