version: "3.9"
services:
  vaadin:
    image: vaadin/my-app
    build: ../../../my-app
    ports:
      - "8080:8080"
    environment:
      - VAADIN_PUSH_URL=/VAADIN/push
  web:
    image: nginx
    volumes:
      - ../../templates/push-url.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "9090:80"
    environment:
      - VAADIN_PATH=/
      - VAADIN_PUSH_PATH=/VAADIN/push